apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-deployment
  labels:
    app: name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
      - name: name-container
        image: lhchi04/name:v1
        ports:
        - containerPort: 5000
        env:
          - name: DATA_MICROSERVICE
            valueFrom:
              configMapKeyRef:
                name: name-config-map
                key: DATA_MICROSERVICE

