apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  namespace: pan-main
  labels:
    app: main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main-container
        image: lhchi04/main:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: DATA_MICROSERVICE
            valueFrom:
              configMapKeyRef:
                name: main-config-map
                key: DATA_MICROSERVICE

