apiVersion: v1
kind: Service
metadata:
  name: main-svc
  namespace: pan-main
spec:
  type: NodePort
  selector:
    app: main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31318