apiVersion: v1
kind: Service
metadata:
  name: pantry-svc
  namespace: pan-pantry
spec:
  type: NodePort
  selector:
    app: pantry
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 31319