apiVersion: apps/v1
kind: Deployment
metadata:
  name: pantry-deployment
  namespace: pan-pantry
  labels:
    app: pantry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pantry
  template:
    metadata:
      labels:
        app: pantry
    spec:
      containers:
      - name: pantry-container
        image: lhchi04/pantry:0.1.4
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5003
        env:
          - name: DATA_MICROSERVICE
            valueFrom:
              configMapKeyRef:
                name: pantry-config-map
                key: DATA_MICROSERVICE

