apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-deployment
  namespace: pan-recipe
  labels:
    app: recipe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipe
  template:
    metadata:
      labels:
        app: recipe
    spec:
      containers:
      - name: recipe-container
        image: lhchi04/recipe:0.1.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5004
        env:
          - name: DATA_MICROSERVICE
            valueFrom:
              configMapKeyRef:
                name: recipe-config-map
                key: DATA_MICROSERVICE

