apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: pan-user
  labels:
    app: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-container
        image: lhchi04/user:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
          - name: DATA_MICROSERVICE
            valueFrom:
              configMapKeyRef:
                name: user-config-map
                key: DATA_MICROSERVICE

