apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: pan-user
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 31315