apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  labels:
    app: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main-container
        image: lhchi04/main:v1
        ports:
        - containerPort: 5000
        env:
          - name: DATA_MICROSERVICE
            valueFrom:
              configMapKeyRef:
                name: main-config-map
                key: DATA_MICROSERVICE

