apiVersion: apps/v1
kind: Deployment
metadata:
  name: pantry-deployment
  labels:
    app: pantry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pantry
  template:
    metadata:
      labels:
        app: pantry
    spec:
      containers:
      - name: pantry-container
        image: lhchi04/pantry:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        env:
          - name: DATA_MICROSERVICE
            valueFrom:
              configMapKeyRef:
                name: pantry-config-map
                key: DATA_MICROSERVICE

