apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: lhchi04/hello:v1
        ports:
        - containerPort: 5000
        env:
          - name: DATA_MICROSERVICE
            valueFrom:
              configMapKeyRef:
                name: hello-config-map
                key: DATA_MICROSERVICE

