apiVersion: v1
kind: Service
metadata:
  name: hello-service-svc
spec:
  type: NodePort
  selector:
    app: hello-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31314